services:
  - type: web
    name: mini-crm-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://bhargavi2005.github.io
      - key: MONGO_URI
        value: mongodb+srv://bhargavi:bhargavi111@cluster0.z7ptqcz.mongodb.net/mini-crm?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: minicrm_super_secret_key_2024_bhargavi
      - key: JWT_EXPIRES_IN
        value: 7d
